# Set the kitty theme based on the dark-mode stotus
alias kdark='kitty @ set-colors -a ~/.kitty-dark.conf'
alias klight='kitty @ set-colors -a ~/.kitty-light.conf'
is_dark=$(dark-mode status)
if [ "$is_dark" = "on" ];
then
  kdark
else
  klight
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/Users/griffin//homebrew/bin:$PATH
export PATH=$PATH:/Users/griffin/.foundry/bin
export PATH=./bin:${PATH}
export PATH=/usr/local/bin:/usr/local/sbin:~/bin:$PATH

# Include local node_modules in path
export NODE_PATH=node_modules/

# Android Studio
export ANDROID_HOME="/Users/griff/Library/Android/sdk/"
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

export ANDROID_HOME=~/Library/Android/sdk && export PATH=${PATH}:${ANDROID_HOME}/tools && export PATH=${PATH}:${ANDROID_HOME}/platform-tools && export ANDROID_SDK_ROOT=~/Library/Android/sdk


JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home"
export JAVA_HOME
export PATH="$PATH:$JAVA_HOME/bin"
#
#export PATH="/usr/local/opt/openjdk@8/bin:$PATH"
#export PATH="~/Library/Java/JavaVirtualMachines/zulu8/bin:$PATH"

# Python
export PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"
#ZSH_THEME="griffin"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  gitfast
  git-extras
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

### Github Token
export GITHUB_NPM_TOKEN=

### Defined Logging Aliases
alias dlogs='AWS_PROFILE=dev aws logs tail --follow --format short $(aws logs describe-log-groups | jq -r ".logGroups[].logGroupName" | fzf)'
alias slogs='AWS_PROFILE=staging aws logs tail --follow --format short $(AWS_PROFILE=staging aws logs describe-log-groups | jq -r ".logGroups[].logGroupName" | fzf)'
alias plogs='AWS_PROFILE=production aws logs tail --follow --format short $(AWS_PROFILE=production aws logs describe-log-groups | jq -r ".logGroups[].logGroupName" | fzf)'

### Pikalytics EC2 SSH
alias  pika='ssh -i ~/Keys/pikalytics.pem ec2-user@34.197.205.97'


### QOL Aliases
alias grep='grep -n --color'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias python3='python3.10'

### powerlevel10k
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

### Alternative to gitfast plugin to reduce git latency
#__git_files () {
#    _wanted files expl 'local files' _files
#}

### zsh-autosuggestion config
# Bind tab to maintain bash-like tab completion
#bindkey '^I' forward-word
# Use history first, fallback to standard auto-completion
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
# Skip underscores in forward-word
WORDCHARS+='_.'

if [[ $OSTYPE == darwin* && $CPUTYPE == arm64 ]]; then
  alias brew=/Users/griffin//homebrew/bin/brew
else
  alias brew=/usr/local/bin/brew
fi

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=5'

# bun completions
[ -s "/Users/griffin/.bun/_bun" ] && source "/Users/griffin/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
